### ISSUE TITLE
Query "get transactions by block id" block_id size limitation

### ISSUE THREAD

**Issue by SaumyaO** [cakcora/Chainoba#20]
Hello All,

Thanks for the data provided.

We tried to get the details of block for 1 day using the api : get transactions by block id but we received an error saying request can be done for only 5 blocks(PFA for reference). Is it possible to remove the restrictions as we need to provide analysis on atleast daily basis.

Regards,
Saumya

![issue1](https://user-images.githubusercontent.com/56184814/67989476-ebeeb500-fc00-11e9-8d2e-54d29d3c44d2.png)

**Comment by mahyamaftouni** [comment]
This restriction is because of the volume of data (there are transactions with more than a hundred inputs and outputs). The endpoint might timeout for a large input parameter list. 
You can achieve what you want by iterating on your transaction ids and calling the API multiple times.

**Comment by SaumyaO** [comment]
Thanks

**Comment by cakcora** [comment]
A day has around 144 blocks, getting all blocks in one go will take 144 MBs of data (maximum).

**Comment by cakcora** [comment]
It is better to use small numbers of blocks
