### ISSUE TITLE
node features

### ISSUE THREAD

**Issue by cakcora** [cakcora/Chainoba#38]
Saad is doing clustering with node features, and the graph team is creating node features as well (for bitcoin for now, but ethereum will be there too).

Saad, please talk to the graph team to get the features from them directly.

**Comment by SaadBenn** [comment]
@tadepask @srija-srivast @SaumyaO When do you guys think the implementation would be done for this task?

**Comment by srija-srivast** [comment]
Hi @SaadBenn  ,
We'll update you with the implementation soon. So please give us some time.

**Comment by srija-srivast** [comment]
Hi @SaadBenn , @cakcora ,
Could you please explain us with an example, how you want our analysis data.

Thank you

**Comment by SaadBenn** [comment]
`194317 194318 1524611855 68533832870000000000` 
The format of the above line is `fromAddress`, `toAddress`, `UnixTimeStamp`, `Amount`. You guys should be able to give me features from the dataset. For instance, one features could be the number of times an Address was used in transactions, another could be the total amount sent from/to by that address etc. These are just some features. I am sure @cakcora can guide you better.

**Comment by cakcora** [comment]
Saad needs whatever node features you are computing on the graph. We talked about this. Also, he does not care if data comes from bitcoin or ethereum blockchains.

**Comment by SaumyaO** [comment]
Hi @SaadBenn , @cakcora 

Ok, so you want node feature on address graph because we are doing analysis on composite graph. So will be providing you with graph object where each node will have its attribute set according to node feature that we will be extracting. Please confirm if we are on the same page.

Thank you

**Comment by cakcora** [comment]
Graph itself is not needed. Only a table is enough

**Comment by SaadBenn** [comment]
> Hi @SaadBenn , @cakcora
> 
> Ok, so you want node feature on address graph because we are doing analysis on composite graph. So will be providing you with graph object where each node will have its attribute set according to node feature that we will be extracting. Please confirm if we are on the same page.
> 
> Thank you

It'd be nice if you guys can give me the features soon. @srija-srivast @SaumyaO
