### ISSUE TITLE
Creating a table for Ponzi Schemes

### ISSUE THREAD

**Issue by kgovil2009** [cakcora/Chainoba#41]
@mahyamaftouni @maheshkkumar @JasmineRandhawa @mariowr2 I have added a file in the anomaly folder which has the data for the Ponzi Schemes (PonziData.txt). Based on the discussion with @cakcora could you please create a table with the mentioned column names? I will need this data and then hit Etherscan API to fetch the smart contract code from there.
@cakcora Please let me know if I missed something.

**Comment by maheshkkumar** [comment]
Hi, 

For the Ponzi scheme API, do you need the functionality of inserting new data to the table or only to query the data in the file that you have provided?

Let us know.

**Comment by kgovil2009** [comment]
Hi Mahesh

I only need to query the data that I have provided. The address and the label "Ponzi" are to be returned when I call.

Thanks

**Comment by maheshkkumar** [comment]
Thank you, we have populated the tables, we are finishing up the API and will let you know once it is completed.

**Comment by kgovil2009** [comment]
@JasmineRandhawa I have created a pull request which has the file Nonponzi.txt, the data in the same is to be added in the previously created table. Could you please let me know once that is done?
Thanks!
CC: @cakcora

**Comment by mariowr2** [comment]
cakcora/Chainoba wrote:

@JasmineRandhawa I have created a pull request which has the file Nonponzi.txt, the data in the same is to be added in the previously created table. Could you please let me know once that is done?
Thanks!
CC: @cakcora

**Comment by JasmineRandhawa** [comment]
Sure Karan.Will let you know once done

**Comment by JasmineRandhawa** [comment]
Hey Karan,

The data has been loaded. Please let us know in case of any issues.

Thanks
Jasmine

**Comment by kgovil2009** [comment]
Thanks Jasmine!
