### ISSUE TITLE
Storing address features in database

### ISSUE THREAD

**Issue by srija-srivast** [cakcora/Chainoba#46]
Hi @maheshkkumar , @mahyamaftouni  , @JasmineRandhawa , @mariowr2 , @cakcora ,

We want to store the addresses' features on daily basis and when required we must be able to retrieve it for  our analysis purpose, as discussed in today's class.
We would need the following columns to store the details:
- Address
- Date
- No_of_SCC
- No_of_WCC
- BTC_Received
- BTC_Sent
- Activity_Level
- Clustering_Coeff
- PearsonCC
- Maximal_Balance
- Current_Balance

Kindly provide us a function which will store and retrieve the above details.
Can you please  let us know by when we can get the requested functions.

Thanks

**Comment by maheshkkumar** [comment]
Hi @srija-srivast thank you providing the details. Can you also specify the corresponding data types for all the fields. We will try to get this done by tomorrow. Thank you.

**Comment by srija-srivast** [comment]
Hi @maheshkkumar ,

Please find the data types as below:
- Address -- varchar
- Date -- date
- No_of_SCC -- integer
- No_of_WCC -- integer
- BTC_Received -- integer
- BTC_Sent -- integer
- Activity_Level -- integer
- Clustering_Coeff -- float8
- PearsonCC -- float8
- Maximal_Balance --integer
- Current_Balance --integer

**Comment by mahyamaftouni** [comment]
@srija-srivast the latest version is not deployed yet. I will let you know whenever it is deployed and I will add sample requests for you in the postman collection.

**Comment by mahyamaftouni** [comment]
@srija-srivast The latest version in deployed. let me now if you have any questions or problems
