### ISSUE TITLE
Ethereum API not working

### ISSUE THREAD

**Issue by SaumyaO** [cakcora/Chainoba#61]
Hi, @maheshkkumar , @mahyamaftouni , @JasmineRandhawa , @mariowr2 , @cakcora 

We tried calling the ethereum API but its not working
Please find the attached screenshot.
![Screenshot 2019-11-28 at 2 54 45 PM](https://user-images.githubusercontent.com/56184814/69831459-1a0ae900-11ef-11ea-84ca-f6bfad3edfad.png)

We also tried calling ethereum API through code and its shoots 404 error.

Kindly guide us.

Thank You

**Comment by maheshkkumar** [comment]
Hi, 

We have not deployed the latest changes to the server as we are currently populating the DB. The ethereum data consists of close to 3 million rows, so it is taking a while to insert them to the DB. We will let you know once it is done. 

Thank you.

**Comment by SaumyaO** [comment]
Thank you so much for the updates

**Comment by maheshkkumar** [comment]
Hi,

The ethereum API is deployed and please take the latest pull. Also, use 6000 for the port when calling the API. 

Let us know if you need any help.
