### ISSUE TITLE
Clarification regarding Bitcoin data

### ISSUE THREAD

**Issue by tadepask** [cakcora/Chainoba#7]
Hello,
Could you please clarify the following queries regarding the BitCoin API documentation.
1) Where to find the transaction amount?
2) Where the Input/Output addresses are stored?
3) What data is represented by "hash" in the Address type and also in the Transaction type?

Address and transaction hash are the identifiers. Please explain in detail the identifiers?

Thank you
Tadepalli Sarada Kiranmayee

![Screenshot from 2019-10-21 15-07-00](https://user-images.githubusercontent.com/56170232/67244479-65c3b900-f41f-11e9-9c7a-9b53a3b15054.png)
![Screenshot from 2019-10-21 15-09-34](https://user-images.githubusercontent.com/56170232/67244480-65c3b900-f41f-11e9-972e-79a9476a6e91.png)

**Comment by maheshkkumar** [comment]
@tadepask The API documentation is not finalized yet, we will update it soon and will let you know.

**Comment by maheshkkumar** [comment]
Please refer to the attached PDF that contains the example **request** and **response** formats for the APIs. We are currently working on the official documentation.

I will keep this issue (#7) open as the attached documentation might be helpful for others to know more about the API formats. 

Feel free to comment if any component is unclear in the attached document. 

[endpoints_doc.pdf](https://github.com/cakcora/Chainoba/files/3763688/endpoints_doc.pdf)

**Comment by tadepask** [comment]
Hello,

The document provided i.e endpoints_doc.pdf (in the comment above) and 159.203.28.234:8000(API documentation to use the endpoints to query blockchain data) seems ambiguous to us. Please provide one detailed documentation so that we all are on the same page.

Thanks.

**Comment by mariowr2** [comment]
Hi,
If you have more questions, please refer to the [sample postman project](https://github.com/cakcora/Chainoba/tree/master/foundations/postman_request_templates). The PDF guide is meant as a general description, but when using our API we have already provided all requests to all endpoints pre-populated for easier use. Please import to your Postman instance and let me know if you have any more questions.

**Comment by srija-srivast** [comment]
Hello all,

We have called the API corresponding to "**get transactions inputs by trasanction id**" for many transactions. We have observed that the values of "**prevout_hash**"and  "**prev_output_id**" do not change.
We need "**prevout_hash**" and "**prev_output_id**" values to construct the graph. 

Can you please verify and let us know (PFA for reference). 



![get transactions inputs by trasanction id](https://user-images.githubusercontent.com/56181823/67893806-4b779280-fb25-11e9-9521-be5db2a03b9f.png)

**Comment by mahyamaftouni** [comment]
Hello,

prev_output_id referring the auto-generated id for the previous
transaction output (which is an integer) and prevout_hash is the hash of
the previous transaction.

prevout_hash and prevout_n together can identify exact transaction
output (for further reading <https://learnmeabitcoin.com/guide/vout>).

We decided to add prev_output_id in our API as well to make things easier.


Inputs of transactions in genesis block do not refer to any previous
transactions, and that's why there is no pev_output_id and prevout_hash is
'000...00'.

**Comment by srija-srivast** [comment]
Hi Mahya,

I agree with what you said.
But when we called the API for "get transactions inputs by trasanction id" for transaction id = 26948 (date: November 10, 2009 ; block id =26779), we received the same details as observed previously. 
PFA for reference.

As you have mentioned above "prevout_hash and prevout_n together can identify exact transaction
output", for the same reason we require this data to build the graph. But we get the same values of  **prevout_hash,** **prevout_n**, **sequence**, and **prev_output_id** for every transactions  apart from the ids and scriptsig. 
And if there is any instance for which you get different values the mentioned attributes, then could you please share the information for the same?

Kindly verify this.

If the above queries are still trivial, can we please meet and discuss.

Thanks.
![11-10- t26948](https://user-images.githubusercontent.com/56181823/67897826-2ab33b00-fb2d-11e9-9413-99c6c0580bad.png)

**Comment by mahyamaftouni** [comment]
transaction with id = 26948 has hash  = "e37f5ac80fd837656e324c05965f0786d3f47e753e31886f70a7f8771c351536" which is equivalent of [this transaction](https://www.blockchain.com/btc/tx/e37f5ac80fd837656e324c05965f0786d3f47e753e31886f70a7f8771c351536) and does not have a reference to any output. 
(transaction hash is added in the transaction endpoint and will be deployed soon)

for example transaction with id = 172 have an input with non-null prev_output_id.
